:schedule:
  scraper:
    cron: '0 0 1 * * Europe/Bucharest'   # Runs monthly at 00:00
    class: ScraperWorker
    queue: scheduler
  bigchaindb:
    cron: '30 0 1 * * Europe/Bucharest'
    class: BigchaindbWorker
    queue: bigchain
